name: Test
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}/nuget-5.0.x/${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}/nuget-5.0.x/
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}/node-16/${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}/node-16/
      - name: Install Dependencies
        run: make install
        env:
          PERCY_POSTINSTALL_BROWSER: true
      - name: Run Tests
        run: make test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
